'use strict';

openfdaviz.controller('TypeaheadController', ['$scope', function($scope) {
  $scope.selected = undefined;
  $scope.terms = [  // Drugs
                    'hydrocodone',
                    'lipitor',
                    'synthroid',
                    'hydrochlorothiazide',
                    'zithromax',
                    'furosemide',
                    'toprol-xl',
                    'albuterol aerosol',
                    'motrin',
                    'nexium',
                    'prednisone',
                    'metoprolol',
                    'levoxyl',
                    'plavix',
                    'effexor xr',
                    'coumadin',
                    'tylenol',
                    'klonopin',
                    'neurontin',
                    'flonase',
                    'naproxen',
                    'rx',
                    'pharmaceuticals',
                    'pharmacy',
                    'injectable',
                    'bottle',
                    'tablets',
                    'vial',
                    'sodium',

                    // Foods
                    'beans',
                    'grains',
                    'eggs',
                    'fish',
                    'pork',
                    'tomato',
                    'cucumber',
                    'fruits',
                    'nuts',
                    'dairy',
                    'milk',
                    'beef',
                    'leafy greens',
                    'poultry',
                    'chicken',
                    'yogurt',
                    'packaged',
                    'plastic',
                    'salad',
                    'fresh',
                    'bags',
                    'cream',
                    'packed',
                    'ingredients',
                    'butter',
                    'cheese',
                    'chocoloate',
                    'herb',
                    'ice',
                    'salt',
                    'sugar',
                    'carton',

                    // Devices
                    'defibrillator',
                    'artificial hip',
                    'pacemaker',
                    'implants',
                    'screws',
                    'rods',
                    'artificial discs',
                    'intra-uterine devices',
                    'pins',
                    'plates',
                    'pumps',
                    'artificial knee',
                    'coronary stent',
                    'ear tube',
                    'artificial lenses',
                    'surgical',
                    'device',
                    'sterile',
                    'patient',
                    'medical',
                    'systems',
                    'procedures',
                    'blood',
                    'tissues',
                    'kit',
                    'diagnostic',
                    'patient',
                    'pack',
                    'instruments',
                    'surgery',
                    'vitro',
                    'material',
                    'laparoscopic'
                 ];
}]);