'use strict';

openfdaviz.controller('TypeaheadController', ['$scope', function($scope) {
  $scope.selected = undefined;
  $scope.terms = [  // Drugs
                    'Hydrocodone',
                    'Lipitor',
                    'Prinivil',
                    'Tenormin',
                    'Synthroid',
                    'Amoxidillin',
                    'Hydrochlorothiazide',
                    'Zithromax',
                    'Furosemide',
                    'Norvasc',
                    'Toprol-XL',
                    'Xanax',
                    'Albuterol Aerosol',
                    'Prilosec',
                    'Zoloft',
                    'Zocor',
                    'Glucophage',
                    'Motrin',
                    'Dyazide',
                    'Ambien',
                    'Keflex',
                    'Nexium',
                    'Prevacid',
                    'Lexapro',
                    'Prednisone',
                    'Zyrtec',
                    'Singulair',
                    'Celebrex',
                    'Prozac',
                    'Fosamax',
                    'Metoprolol',
                    'Premarin',
                    'Levoxyl',
                    'Ativan',
                    'Allegra',
                    'Plavix',
                    'Effexor XR',
                    'Micro-K Extencaps',
                    'Protonix',
                    'Propoxyohene',
                    'Advair Diskus',
                    'Coumadin',
                    'Tylenol',
                    'Klonopin',
                    'Neurontin',
                    'Flonase',
                    'Elavil',
                    'Zantac',
                    'Desyrel',
                    'Naproxen',
                    'Augmentin',

                    // Foods
                    'Beans',
                    'Grains',
                    'Mollusks',
                    'Eggs',
                    'Fish',
                    'Pork',
                    'Tomato',
                    'Cucumber',
                    'Fruits',
                    'Nuts',
                    'Dairy',
                    'Milk',
                    'Beef',
                    'Leafy Greens',
                    'Poultry',
                    'Chicken',
                    'Yogurt',

                    // Devices
                    'Defibrillator',
                    'Artificial Hip',
                    'Pacemaker',
                    'Implants',
                    'Screws',
                    'Rods',
                    'Artificial Discs',
                    'Intra-Uterine Devices',
                    'Pins',
                    'Plates',
                    'Pumps',
                    'Artificial Knee',
                    'Coronary Stent',
                    'Ear Tube',
                    'Artificial Lenses'
                 ];
}]);